name: Convert Images to WebP

on:
  schedule:
    - cron: "0 */6 * * *" # 每 6 小时执行一次
  workflow_dispatch: # 支持手动触发

jobs:
  convert-images:
    runs-on: ubuntu-latest

    steps:
    # 检出代码
    - name: Checkout code
      uses: actions/checkout@v3

    # 设置 Node.js
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    # 安装依赖
    - name: Install dependencies
      run: npm install

    # 压缩并转换图片
    - name: Convert images to WebP
      run: node scripts/convert-to-webp.js

    # 提交转换后的图片
    - name: Commit and push changes
      run: |
        git config user.name "GitHub Actions"
        git config user.email "actions@github.com"
        if [ -n "$(git status --porcelain)" ]; then
          echo "Changes detected, committing..."
          git add images/ images.json
          git commit -m "Auto-generate images.json and converted images"
          git push
        else
          echo "No changes to commit, skipping commit and push."
        fi
        exit 0
